version: '3'

volumes:
    postgres_data:
        driver: local

services:
    database:
        image: rethinkdb:latest
        container_name: database
        command: rethinkdb --bind all
        ports:
            - "28015:8080"
            - "28015"
        networks:
            - gateway

    redis_logger:
        image: redis
        container_name: redis_logger
        ports:
            - "6379:6379"
        networks:
            - gateway

    redis_pubsub:
        image: redis
        container_name: redis_pubsub
        command: --port 6380
        ports:
            - "6380:6380"
        networks:
            - gateway

    redis_gateway:
        image: redis
        container_name: redis_gateway
        command: --port 6381
        ports:
            - "6381:6381"
        networks:
            gateway:
                aliases:
                    - redis

    postgres:
        image: postgres
        container_name: keycloak_database
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password
        networks:
            - gateway

    gateway:
        build: ./gateway
        container_name: gateway
        ports:
            - "8080:8080"
            - "80:80"
            - "8443:8443"
            - "9876:9876"
        volumes:
            - ./gateway/config/system.config.yml:/usr/src/app/config/system.config.yml
            - ./gateway/config/gateway.config.yml:/usr/src/app/config/gateway.config.yml
        restart: always
        networks:
            - gateway

    user:
        build: ./
        container_name: user
        entrypoint: sh -c 'npm install; npm run start:dev'
        restart: always
        ports: 
            - "3010:3010"
            - "3800:3800"
        environment:
            CHOKIDAR_USEPOLLING: 1
            SERVICE_NAME: user
            SERVICE_PORT: 3010
            SERVICE_ENV: local
        volumes:
            - ./src:/app/src
        depends_on:
            - gateway
        networks:
            - gateway

    landingpage:
        container_name: landingpage
        restart: always
        image: assetory/landingpage:local
        ports: 
            - "3000:3000"
        depends_on:
            - gateway
        networks:
            - gateway

    dashboard:
        container_name: dashboard
        restart: always
        image: assetory/dashboard:local
        ports: 
            - "3005:3005"
        depends_on:
            - gateway
        networks:
            - gateway

networks:
    gateway:
