version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: assetory/user
    docker:
      - image: circleci/node:12

jobs:

  test:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      
      # Install dependencies
      - run:
          name: "install dependencies"
          command: "npm install"

      # Run tests
      - run:
          name: "run tests"
          command: "npm test"

  build-develop:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      
      # Install dependencies
      - run:
          name: "install dependencies"
          command: "npm install"

      # build application
      - run:
          name: "build application"
          command: "npm run build"
      
      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build \
            --build-arg SERVICE_NAME_ARG=$SERVICE_NAME \
            --build-arg SERVICE_PORT_ARG=$SERVICE_PORT \
            --build-arg SERVICE_ENV_ARG=develop \
            -t $IMAGE_NAME:develop . 
      
      # Archive Docker image
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  build-local:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      
      # Install dependencies
      - run:
          name: "install dependencies"
          command: "npm install"

      # build application
      - run:
          name: "build application"
          command: "npm run build"
      
      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build \
            --build-arg SERVICE_NAME_ARG=$SERVICE_NAME \
            --build-arg SERVICE_PORT_ARG=$SERVICE_PORT \
            --build-arg SERVICE_ENV_ARG=local \
            -t $IMAGE_NAME:local .
      
      # Archive Docker image
      - run:
          name: Archive Docker image
          command: docker save -o image_local.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image_local.tar

  build-latest:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      
      # Install dependencies
      - run:
          name: "install dependencies"
          command: "npm install"
      
      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build \
            --build-arg SERVICE_NAME_ARG=$SERVICE_NAME \
            --build-arg SERVICE_PORT_ARG=$SERVICE_PORT \
            --build-arg SERVICE_ENV_ARG=prod \
            -t $IMAGE_NAME:latest . 
      
      # Archive Docker image
      - run:
          name: Archive Docker image
          command: docker save -o image_latest.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image_latest.tar

  publish-local:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker

      # Load archived Docker image
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image_local.tar
      
      # Publish Image to DockerHub
      - run:
          name: Publish Image to DockerHub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:local

  publish-develop:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker

      # Load archived Docker image
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      
      # Publish Image to DockerHub
      - run:
          name: Publish Image to DockerHub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:develop

  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker

      # Load archived Docker image
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image_latest.tar
      
      # Publish Image to DockerHub
      - run:
          name: Publish Image to DockerHub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

  deploy-develop:
    executor: docker-publisher
    steps:

      # deploy image to digitalocean...
      - run: 
          command: |
            ssh -oStrictHostKeyChecking=no -v root@$IP \
            "cd ~/gateway && sh deploy.develop.sh"


workflows:
  version: 2
  workflow:
    jobs:
      - test:
          filters:
            branches:
              only:
                - develop
      - build-local:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
      - publish-local:
          context: dockerhub
          requires:
            - build-local
      - build-develop:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
      - publish-develop:
          context: dockerhub
          requires:
            - build-develop
      - deploy-develop:
          context: digitalocean
          requires:
            - publish-develop

      - build-latest:
          filters:
            branches:
              only:
                - master
      - publish-latest:
          context: dockerhub
          requires:
            - build-latest
